### ISSUE TITLE
It seems that the website is down

### ISSUE THREAD

**Issue by pseudonymus** [reduxframework/WPDemo#2]
Hey guys,

It seems that wpdemo.io is down. Are you still maintaining the tool? 

Thanks!
Madalin

**Comment by dovy** [comment]
Sorry no. My partner in the operation decided to part ways and take the source. WPDemo is gone.  :(

**Comment by pseudonymus** [comment]
I'm really sorry to hear that. Well, I`m actually loving the plugin and I`m having a small issue https://github.com/reduxframework/redux-framework/issues/3081 

Are you aware of a newer version of WpDemo.io after v1.1 which I could try out, since the v1.1 which I`m running is not working with ReduxFramework newer than v3.5? 

Thanks!

**Comment by dovy** [comment]
Nope.  :(

You're welcome to hack at it and try and get it working.  :)

**Comment by pseudonymus** [comment]
Ok. Cool! Thanks for letting me know!

**Comment by pseudonymus** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

madalintudose@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Your empowr account was reserved for you by madalintudose@gmail.com in order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppTEOENjtiZrsRy1yEtaqJwFOpMpHkFG%2BIcrG1Xd4bN8qn8DROdSRCLmZOqMCeMVyAtnVvr1M7QP5DiHgY6tT1pPn05RqmAwXFlUgHnKC80gWSqkNoWJ4%2FS3LKg0WQ%2BfFBG1ajif8Im2C5kNtLN4BsEk&vet=694&mlid=9318582898&fn=6k5SCVt9Pc7MFO7KXhUvEw%3D%3D.

No more emails from madalintudose@gmail.com (madalintudose@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppTEOENjtiZrsRy1yEtaqJwFOpMpHkFG%2BIcrG1Xd4bN8qn8DROdSRCLmZOqMCeMVyAtnVvr1M7QP5DiHgY6tT1pPn05RqmAwXFlUgHnKC80gWSqkNoWJ4%2FS3LKg0WQ%2BfFBG1ajif8Im2C5kNtLN4BsEk&vet=694&mlid=9318582898&fn=6k5SCVt9Pc7MFO7KXhUvEw%3D%3D

*This promotional email has been sent by madalintudose@gmail.com to reply@reply.github.com. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by pseudonymus** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=fgh3eI9oq5ggYveGgheuoGS0F8tDEz%2b0a9rsT9FaiOq%2fOPqP4gBXpNw%2b4kd7pS2ePLv%2foQSxX%2flRYt8wfiOwSQwT5zj7KNXYG0Nd7ryYFLPTcClfv7ut3fisGrl3ZOER%2beaQYFcT2muBPWZOmgRQ%2fMyzJAyem3PNTfWuuZX%2fGT8t%2bccDh%2brm7itLgVOAAC364kacOqZOVqkPO830FY66Jg1tYq75eFV7jwC%2b8etAbBy0aM29yq72JnRIw%2fJx5nvJJcKmQjo26cPxEC9JbwJ7y35J%2b13SysETXgBYrwXt2mEe2KnOBYHZzqXxD4SvUIBd&amp;PolicyAcceptance=I1qWcwZfD0hmQvu2poAIkZT%2bYzYpdTnz8qkzbQ%2bu0WmAm%2fjKOXXYmqak%2bKe5dO2hsdylcOo5x4kBIqeGhUHpJn0jN%2fuRmPaz5MVnzxmhb46UCq6Dv9pnIc6A4L%2fSolT3VfqjrqWx5gbNjnwtjLpBbmGEQzMsFXgL4g8jWf%2fEGyzQDRz3m2lYFF6SAQYHicyLeal0BA6drWlW6fV0M6HYpc5EjC181NeZ7IV3%2fJbvJR8QjSmhmaFvogv0f2cOYMp%2f%2bBXkQfcqvMEWcObJAk8%2feljenM53bu6RCcSb7wpBxGYk1C%2f6RGI3qFbOHcCB5t1ByYbkRknOKJRRX06PvL%2f09X3u2bdLe7%2fq%2fsYeiNnCcl5M1BOsw7dcRg8AB8aXpP1OQOJvd%2fslQLwJaFAZvg8RMRTu9jc48I2QrVuDEfLE9KbthKciyLMV1hOyGJXmNh9CIhOpqnghJvQgaNJwGV1CSD6pooTiYN3o633OZDpN7LJvbyWcCJbmgswq803dGuehTjEy1d3UdoinHyncgZCWp6xsMDutulPmzjiT5kB2QdNa1pvCvI2f8Jyxmr3ELZScytI97iiZLNEhWEabwebly1oSfiJsA25HV1fvZFpPocqNAmC5knnT8pUf%2bSqTsZ6Gm53uSM%2fxtbOuiJQmYlG7Wi0ODqWuZnK87CXdUSVXliyA%2fbBFBh47UmmlXL386B9tqqv4IhV5jLebt14477a8AHAs2CAbtgwifDBp21Vr8LtHBOnczkA8Htlz7dh0sfHMvU9R2beP%2baA10TLJeEb6dgjEyoB8UBI%2f6P4LFwArZ63OpiUQpor4SJUipmec%2bBZru7JCOovwN0IponNO%2f3bR6t46R8TAKYhxdBdaMLFmLVyzzIu8rJVJEdg%2bQeewkM0oOY5DIG4bSew%2fdlsIBx4LpXrsmJjKbMg8rXUOWgO37%2fmu1U1ydlS3h68oyjRpUiqsp7Xptn%2fujXJOo9YqwdU7lw%3d%3d&amp;vet=745&amp;dt=090417&amp;mlid=9905048833&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=59778959&amp;rt=12:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppTEOENjtiZrsRy1yEtaqJwFOpMpHkFG%2BIcrG1Xd4bN8qn8DROdSRCLmZOqMCeMVyAtnVvr1M7QP5DiHgY6tT1pPn05RqmAwXFlUgHnKC80gWSqkNoWJ4%2FS3LKg0WQ%2BfFBG1ajif8Im2C5kNtLN4BsEk&vet=745&mlid=9905048833.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppTEOENjtiZrsRy1yEtaqJwFOpMpHkFG%2BIcrG1Xd4bN8qn8DROdSRCLmZOqMCeMVyAtnVvr1M7QP5DiHgY6tT1pPn05RqmAwXFlUgHnKC80gWSqkNoWJ4%2FS3LKg0WQ%2BfFBG1ajif8Im2C5kNtLN4BsEk&vet=745&mlid=9905048833

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by pseudonymus** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=F4Is%2fO2JoGdIIA0XoxwPVkCss8%2bolqUEWDRCRTEhwbKv7%2byEULb0xEgzK4GvD%2flyPAile14tKWwkJhGJwvz1hn7V61yD37Hz3mQXfZjb1awxzBOMqofkWvEMDvb36y4v%2buQl6fukxtZ0h9bsWhdxxJ4gvWSFRZJ6USiBDVgaYEJXkG1rSBVlIwgVE0m08nzZD9kUyTtq6KVGLe%2f3r9dTxdQqFrFMvorNhP9pZg52Aty0ekxzXQqutxcEnI1Brh2hvJbvdXrxFIormFaqq0MnqtVRyJfc4YzDt66RSUyVeR5Gcydo5eV4FYtxwX5jw9fb&amp;PolicyAcceptance=qR0RmyrIZxmL1%2bdidSC%2bYvDSemM0qKvT%2bbNFedStBGt%2fTZuLeuiyVhfG6bTvjvByFJ3XIcv0EZYhYaRJ7he%2bZoaIrtK%2btStjKaDv1HgoPuNrbv0jMq1xmH2AQ8m%2byrBwAHiBxSp2DzltQ1nBBVGBvaHZJrDkJnand3thCCmQ26onZ6mzzYmabHyLPAh%2fV7AxCELJpI1UOWsLH1O7Ft6pwjVSb%2buuwykYL2j9tArttMNehSPfC3TTCZQy8QGoYg350xx59Uc5naFkN1OTMULp4hmscHpdVNG30Du5SLsW98GXl9WI749l6Jo4iQwexb8krYldDq%2bT7HarQmfxxhte%2fIMX7WilsjtTzTKCznWExfd5g0TkoZwSPG7BqLuw5kOyGVUvEUwlobQ6dCYFq%2bMkpDVmV0ns8LScmrlh8Vk0kxa%2bYWq44vASGyYzlF9nJrasmk1zTm3cVJz1UbC07Iracjcsz%2beglYKAjcwP8nh5AlwM1qQNAwM4JbCUofNhce3HTbZMvkXELATNhIAcUmeudF3nrKVdNg%2fK7Ud32Oe42MeEBo8G8bJR%2bWv%2fY3QKpZHupf4CLTC37GwclyuvH%2fw0QTxtKAdhNojU4noRbb7PfvocBA5x%2bFiWO4ejYN4H8GLasDuTCzLmFZHgUbtLveugMkXztjGJQ8Vuq1XUvCtcVimioxUR1DFEijPPtC0v3F9hqPso1POquNhr6NFyMNvFeUtvZCqVXXouVcqMarV1WRnLy6UjB0omrkBWrNfbRJp4iwex2VP5WXBICAnFVBVpujW17Wr8Ojk4n%2bM7aiAFqilVG87EF0kLc%2bsEVtfYxwSdXHahweqtJYH5B%2fxCAcfZgRDt0nT%2fcaNb7HKmgD%2fBFEPzJoBTbGO6eDTaNwz3eoLA8NErkaenC3GaevNIGpFakyCjoYkLURcMnMkT%2fQHjiKiQkqGskAq%2biMbAZU439zQY&amp;vet=760&amp;dt=010118&amp;mlid=10123838375&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=59778959&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA

**Comment by pseudonymus** [comment]
body { -ms-text-size-adjust: none !important; font-family:'Helvetica Neue', Helvetica, Arial, sans-serif;}

My balance: $1,000

Home

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

&nbsp;

p

small-text

Hello,

Starting in 2016, you were an early (alpha) member of our project called empowr. Well, that project evolved and became the new www.empowr.com. Along the way, we invented virtual currency and many other technologies used by all the top social media companies.

Your free coins

As you probably know by now, empowr is launching its own coin (like Bitcoin) and, as our way of saying Thank You to the incredible community that got us here, we're giving the first coins to you – TOTALLY FREE. Read the details
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=18&amp;authToken=zelXsKiTvvfZWqLKoydDJU9ciR2dIkH6%2fpLAGoAc6zVduKLyJd%2bCrsI0TpuFoV10zbV5HS04OM3nv1QX%2f2%2b702%2fh5YggCSs4he1JEpx8MZEESr0GFLglf5XGlHGU5v1t7nEWTp%2f9fzYke%2fsCT9GUDOBDlhBsa7Jt3X9S7t3IOb%2fregVfUH1R9udTZoKoQVJeYS02UN1dE8IRXRAvD%2bCHMunE%2bMFhyyd52VN6xovLC164LDov48r%2b8aspc2kARox7SY8OWlo6K%2fL%2b%2fgdp9JonDTnPAZqkgppIfxylg6hrJ725GNNx%2bWAcHspZnI6BfjA8&amp;PolicyAcceptance=I8syiwED70H6DNGixIpuDTwlnczhcpORRMKHW%2fMI68XzVWYsSfV0byPsEgPu%2fJTn23pzSbuE4qG4JORwpcB0Edr%2b0jQU%2bJ4qhDtsP1n0Y72dIrXNHZGTHlwmLWZ6oY8AbWZVhzGiOrElTwTbPhDedFVmKSUNOTox9oWQPiJLHQd%2fpXbnYplucn3NlLN%2bEM4Y7JXhSDEcFchnkYGaPRsC9F16ev5GyDcRMvL6ZG9TO9GsnRAwD3%2fbqR4SJuEzAU2LiTmdwjYUNsJAZwqxkMQ5chQgtIvkz%2fpQG67I5qPKcSHJ422xXOnX43hNgxNGDSu1Tc7p%2fdLJTakquy7a%2bYwJjpk28r0Q%2bcCd50YHln4UvAfjWFs7cXhiVuQYnt%2fgd7A3zedJPEC26q2BTOpj%2fpfW%2bqlfrE6FeJlv97V3qP0LV3zsTtPglASXDLVIy2WscxxO3Ah7yx4ALH1Q9zCCkBKsrHrAPgvgcYcwKK%2bk9QkL1%2bA1mWV7fQLkov19lJZcCUNIDtR2ElHpNBeYpP7eCj8QTFMoDd0lhZhAX%2bj0L75nowt83vWznfD15PHDVHOcoW0u3VFJhRRQeq8dNbS0AC%2bPcQO7ozrEEyPfvZ3cZgWIhux%2brJRIr6cLdSP8pmIWdDEpzr0uy64mkZNnLOZoqMdCm7CXH0rwV%2f%2fs%2fLE4Lt%2fjD0PEiyuayDHCMcRkclgdVlsa2zoBCf%2bZdQDIcD0JhN4HSHyGCYyPg05XRTjRcGqXFQkHXpIjg9v4qdEcD4TyqIHnn2qdfmneiIoWGTfw%2bnphuIvfNN3OaMmM8KWCT0OcDeu%2f4gf5r51BbmsAtnHhjLlX7W9zpmshZr%2fQdH8%2foPfoTcw2JOgTENDfdfHnun6AAtJs2NWRYY0VHzbD1B6rx23z3%2biRLNH1h0%2bgivFlFqCOx%2fZtx89LPGn%2bLEMyYEHjGmFQG1lncDAeGwCGrlYXA81JxitLhD9h%2f4%2bdhAp2uZNUFBi7TunA7SMxeMFHF5DcFoE%3d&amp;vet=760&amp;dt=021218&amp;mlid=10280690601&amp;tmpID=3378&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=59778959&amp;rt=1

Secure your free coins &#9658;

Note: Unclaimed coins will be auctioned off to the rest of the community. (As an early member, you get exclusive first access to bid on any unclaimed coins).

Once again, THANK YOU.
-Your friends at empowr.com

Your account was reserved for you in order to allocate your free coins, however you must agree to terms and validate before it can be utilized. By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies.

At this moment, empowr can make no guarantees about the current or future price or value of the new empowr cryptocurrency coin, or that it will be ultimately tradeable on one or more public currency exchanges. By accepting your free founder coins, you acknowledge that this offer represents a gift that can be revoked if it is found to not be legal in your state, country or jurisdiction. Vesting and other details apply.

You are receiving this gift and email because you were an alpha user of the SMS.ac / FanBox / empowr project. You can unsubscribe here
#.

-->

New! Download the empowr mobile app:

&nbsp;

&nbsp;

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: FanBox Terms and Conditions. You can prevent future emails here.
FanBox - 611 K Street, Suite B411, San Diego, CA 92101, USA

**Comment by dovy** [comment]
Sucks the virus you have. haha.
